---
dependencies:
  - name: rabbitmq
    version: ~8.26.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: postgresql
    version: ~10.3.18
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~10.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: 10.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
